### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Luismi28** [TridentMC/CarpentryCubes#1]
@TridentMC Will you update the mod to version 1.14.4?

**Comment by CalmBit** [comment]
Backports to 1.14.4 aren't currently being considered. Sorry.

**Comment by CalmBit** [comment]
To clarify: Backports to 1.14 at this point in time take more effort than it's worth to support mod setups that are (hopefully) gradually moving towards more updated versions. We're officially two versions out from 1.14, and although the speed of mod updates is glacially slow, it's difficult for us to take progress we've made in changing systems around and then apply it backwards. It rarely is clean, and the benefits are outweighed by the amount of time and effort it takes to do things like this.

**Comment by Luismi28** [comment]
Ok adiós máster :v
